export const STANDALONE_WORKER = "STANDALONE_WORKER";
export const STANDALONE_WORKER_START = `${STANDALONE_WORKER}_START`;
export const STANDALONE_WORKER_STOP = `${STANDALONE_WORKER}_STOP`;

export const PROCESS_IMAGE_DATA = "PROCESS_IMAGE_DATA";
export const PROCESS_IMAGE_DATA_REQUEST = `${PROCESS_IMAGE_DATA}_REQUEST`;
export const PROCESS_IMAGE_DATA_DONE = `${PROCESS_IMAGE_DATA}_DONE`;
