export const MAIN = "MAIN";
export const MAIN_SET_CONTEXT = `${MAIN}_SET_CONTEXT`;
export const MAIN_DRAW_REQUEST = `${MAIN}_DRAW_REQUEST`;
export const MAIN_DRAW_DONE = `${MAIN}_DRAW_DONE`;
export const MAIN_IMAGE_DATA_DONE = `${MAIN}_IMAGE_DATA_DONE`;

export const SATELLITE = "SATELLITE";
export const SATELLITE_SET_CONTEXT = `${SATELLITE}_SET_CONTEXT`;
export const SATELLITE_DRAW_REQUEST = `${SATELLITE}_DRAW_REQUEST`;
export const SATELLITE_DRAW_DONE = `${SATELLITE}_DRAW_DONE`;

// TODO remove
export const PROCESS_IMAGE_DATA = "PROCESS_IMAGE_DATA";
export const PROCESS_IMAGE_DATA_REQUEST = `${PROCESS_IMAGE_DATA}_REQUEST`;
export const PROCESS_IMAGE_DATA_DONE = `${PROCESS_IMAGE_DATA}_DONE`;

export const ERROR = "ERROR";
