export const MAIN = "MAIN";
export const MAIN_SET_CONTEXT = `${MAIN}_SET_CONTEXT`;
export const MAIN_DRAW_REQUEST = `${MAIN}_DRAW_REQUEST`;
export const MAIN_DRAW_DONE = `${MAIN}_DRAW_DONE`;
export const MAIN_IMAGE_DATA_DONE = `${MAIN}_IMAGE_DATA_DONE`;

export const SATELLITE = "SATELLITE";
export const SATELLITE_SET_CONTEXT = `${SATELLITE}_SET_CONTEXT`;
export const SATELLITE_DRAW_REQUEST = `${SATELLITE}_DRAW_REQUEST`;
export const SATELLITE_DRAW_DONE = `${SATELLITE}_DRAW_DONE`;

export const PROCESS_IMAGE_DATA = "PROCESS_IMAGE_DATA";
export const PROCESS_IMAGE_DATA_REQUEST = `${PROCESS_IMAGE_DATA}_REQUEST`;
export const PROCESS_IMAGE_DATA_DONE = `${PROCESS_IMAGE_DATA}_DONE`;

export const ERROR = "ERROR";

export const STANDALONE_WORKER = "STANDALONE_WORKER";
export const STANDALONE_WORKER_START = `${STANDALONE_WORKER}_START`;
export const STANDALONE_WORKER_STOP = `${STANDALONE_WORKER}_STOP`;

export const MODULE_WORKER = "MODULE_WORKER";
export const MODULE_WORKER_START = `${MODULE_WORKER}_START`;
export const MODULE_WORKER_STOP = `${MODULE_WORKER}_STOP`;
